### ISSUE TITLE
Concentration filenames

### ISSUE THREAD

**Issue by TimotheeBrgs** [IAMconsortium/concordia#28]
Hello,

Feel free to ask to move this issue somewhere else as it relates to concentration files, not emission files.

It would be useful to inform users about the meaning of the different labels of the concentration filenames. Most of the filenames follow input4MIPs convention but there is still some RESCUE-specific terms that are not so self-explanatory and that could be worth to explain either using e.g., a README file or the netcdf metadata.

Example:
mole-fraction-of-nitrous-oxide-in-air_input4MIPs_GHGConcentrations_RESCUE_IIASA-PIK-REMIND-MAgPIE_3.2.0-4.6.7-RESCUE-Tier1-Extension-2023-09-21-PkBudg_cp0400-OAE_off-2023-10-23_gr1-GMNHSH_2015-2100.nc

I don't understand the meaning of these tags:
- "Direct" vs. "Extension". Both cases end in 2100 whereas I would have expected a latter end date than 2100 for the extension.
- The first instance of a date version. The second instance seems to be the file version, fitting the date tag of the upper directory. The first instance is probably the date version of the Tier1-Direct/Extension case but it could be clarified.
- Baseline / EocBudg_cpXXX / PkBudg_cpXXX
- GMNHSH. Apparently grid-related according to the metadata.

Thank you.

**Comment by gidden** [comment]
@tgasser FYI

**Comment by tgasser** [comment]
Sorry for seeing this only know, as the generation of concentrations files is a separate process from the emissions. Thanks Matt for forwarding!

The files names follow the input4MIPs convention, and the issue is essentially that the current scenario name is: 
`IIASA-PIK-REMIND-MAgPIE_3.2.0-4.6.7-RESCUE-Tier1-Extension-2023-09-21-PkBudg_cp0400-OAE_off-2023-10-23`. 

This is obviously not ideal, but we've reused the names provided to us by the IAM team. We'll harmonize that with the emissions files team for the final version.

FYI:
* "Direct" vs. "Extension", no difference for now because no extension available
* 2 dates are indeed: first, emissions scenarios version, second, concentrations scenarios version
* Baseline / EocBudg_cpXXX / PkBudg_cpXXX is the actual name of the scenarios
* GMNHSH was used in input4MIPs for files providing global / north-hemispheric / south-hemispheric values

**Comment by TimotheeBrgs** [comment]
Indeed, sorry for putting this here, thanks Matt for forwarding and thank you @tgasser for the clarifying explanations.
