### ISSUE TITLE
Revisions to harmonization draft

### ISSUE THREAD

**Issue by gidden** [IAMconsortium/concordia#9]
Following our discussion on 2023-08-16:

- [x] inquire with CEDS regarding SSA Energy and Industry VOC (@gidden)
- [x] propose update to historical china CO2 data (@coroa)
- [x] update unharmonized data with extraction sector split and proposed updated sector mapping (@merfort)
- [ ] check and verify new harmonized values and confirm that we wish to move forward with sector split (@coroa)
- [ ] update unharmonized data with OAE emissions directly to their relevant sectors (e.g., transport and industry) instead of reporting as separate OAE sector (@merfort)

Mattermost discussion regarding CO2:

> @gidden 
> Let me start a separate thread on harmonization issues - and please let me know if you would like me to put this on github as well for posterity. 
> I am looking at the results for the [cp044-OAE_off run](http://rescue-task1.3.s3-website.eu-north-1.amazonaws.com/harmonization/harmonization-2023-08-07-facet-PkBudg_cp0400-OAE_off.html#co2-total). Note that there are now significant discrepancies in the near term for CO2. This was not the case for the [previous set of scenario results ](http://rescue-task1.3.s3-website.eu-north-1.amazonaws.com/harmonization/harmonization-2023-07-26-facet-cmip6.html#co2-total).
> It looks like the primary reason for the change between versions is due to revisions in industry (further away) and transportation (previously underestimated, now closer). 

> @nicobauer 
> OK, what about the change from 2015 to 2020. REMIND increases emissions from energy and industry by slightly more than a giga ton of CO2 (1050 Mt more precisely). A look into CEDS shows for the period 2015 to 2019 an increase of 650 and for EDGAR from 2015 to 2018 an increase of 550. Industrial process increased about 100Mt in both cases, but there some tendency towards stagnation. Now a look into BP statistics indicates an increase of energy related emissions by 960MtCO2. The increases are consistent with the energy part (net of process emissions) compared with CEDS and EDGAR.
In REMIND the emissions are mostly driven upwards by the energy supply sector (about 700Mt). In CEDS the increase from 2015 to 2019 is nearly 490Mt and in EDGAR from 2015 to 2018 it is also about 480Mt.
Conclusion: there are differences in the accounting of emissions that imply differences in CO2 emissions 2015. Assuming a change in emissions from 2015 to 2020 of about +1GtCO2 seems reasonable. The increase that I see in the figure for the harmonized data seems too small.

**Comment by merfort** [comment]
Hi all, I uploaded a new version of the emissions (`REMIND-MAgPIE-CEDS-RESCUE-Tier1-2023-10-17.csv`) in the google drive folder. In this version the OAE calcination emissions are reallocated to the 5 end-use subsectors. As explained above, just to have that information, these emissions are still reported in a separate variable
(`CEDS+|9+ Sectors|Emissions|CO2|OAE Calcination Emissions`, I renamed it from named `CEDS+|9+ Sectors|Emissions|CO2|CDR OAE Calcination Emissions` since the term "CDR" is actually misleading). Please make sure to **exclude this variable** from the harmonization and downscaling process, since that would lead to a double accounting.

Furthermore, I reverted the split between `Energy Sector|Extraction` and `Energy Sector|Supply` emissions back so that there is now again just one `Energy` sector.

That should solve the last two remaing issues. 
Please let me know, if there is anythings else.

**Comment by coroa** [comment]
Hi all,

The new version of the emissions have finally made it through our harmonization and reporting pipeline. Find the results on AWS: http://rescue-task1.3.s3-website.eu-north-1.amazonaws.com/harmonization/2023-11-03/ . I kept the split into Modelled and Non-Modelled Energy Sector emissions. 

I think that should conclude this exercise.
